"use strict";
exports.__esModule = true;
var firstVar = "My name is Test";
var index = firstVar.lastIndexOf("Test");
console.log(firstVar);
console.log(index);
var firstNum = 100;
console.log(firstNum);
var firstBoolean = true;
console.log(firstBoolean);
